replicaCount: 1

image:
  repository: latifbey/stock-service
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8084

env:
  MONGODB_URI: "mongodb://mongodb:27017/stockdb"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  KAFKA_SECURITY_PROTOCOL: "SASL_PLAINTEXT"
  KAFKA_SASL_MECHANISM: "PLAIN"
  KAFKA_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required username='user1' password='aVPF9T3kcg';"

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"
serviceAccount:
  create: false
ingress:
  enabled: false
autoscaling:
  enabled: false
