spring.application.name=gatewayAPI
server.port=8080
management.endpoints.web.exposure.include=*
management.endpoint.gateway.enabled=true

spring.cloud.gateway.routes[0].id=userservice
spring.cloud.gateway.routes[0].uri=http://user-service-helmchart:8083
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[1].id=productservice
spring.cloud.gateway.routes[1].uri=http://product-service-helmchart:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/products/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[2].id=orderservice
spring.cloud.gateway.routes[2].uri=http://order-service-helmchart:8081
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/orders/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1
