image:
  repository: latifbey/user-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8083

ingress:
  enabled: false
serviceAccount:
  create: false
autoscaling:
  enabled: false
