image:
  repository: latifbey/api-gateway
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
serviceAccount:
  create: false
autoscaling:
  enabled: false
