{{- range $name, $service := .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}-helmchart
  labels:
    app: {{ $name }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
        - name: {{ $name }}
          image: "{{ $service.image }}"
          ports:
            - containerPort: {{ $service.containerPort }}
          {{- if $service.env }}
          env:
            {{- range $key, $value := $service.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          {{- end }}
  {{- end }}
